version: '3.1'

services:
  adminer:
    build: .
    container_name: my-web-container
    restart: always
    volumes:
      - .:/app/
    ports:
      - 8001:8000
    depends_on:
      - basedb
  basedb:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 33061:3306
    environment:
      MYSQL_DATABASE: nacion
      MYSQL_USER: rodrigo
      MYSQL_PASSWORD: argregg1;
      MYSQL_ROOT_PASSWORD: example



