version: '3.1'

services:
  adminer:
    build: .
    restart: always
    ports:
      - 8001:8080
    depends_on:
      - basedb
  basedb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 33061:3306
    environment:
      MYSQL_DATABASE: nacion
      MYSQL_USER: rodrigo
      MYSQL_PASSWORD: argrgg1;
      MYSQL_ROOT_PASSWORD: example

  
